# Project information
site_name: "Curo Wayline Planner"
site_description: "Curo Wayline Planner is a straightforward wayline management platform that enables users to create new area and waypoint waylines, and ultimately export them as KMZ files. Users can subsequently import these waylines into other platforms like FlightHub 2 or FlytBase to execute flights with connected real devices"
site_author: "spheredrones"
site_url: "https://curo-user-manual.kenstack.io"

# Copyright
copyright: "&copy; 2024 Curo UAV"

# Repository
repo_name: "GitHub"
repo_url: "https://github.com/sphere-drones/documentation"
edit_uri: "https://github.com/sphere-drones/documentation/edit/main/docs"

# Configuration
docs_dir: "docs"
theme:
  name: "material"
  language: "en"
  shortcuts:
    help: 191 # ?
    next: 78 # n
    previous: 80 # p
    search: 83 # s
  palette:
    primary: "blue"
    accent: "orange"
  features:
    - tabs
    - navigation.expand
    - navigation.instant
    - navigation.tracking
    - navigation.tabs.sticky
    - navigation.path
  #font:
  #text: 'Ubuntu'
  #code: 'Ubuntu Mono'
  #icon:
  #logo: 'images/logo.svg'
  #favicon: 'assets/images/favicon.ico'

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - attr_list
  - md_in_html
  - mdx_math:
      enable_dollar_delimiter: true
  - toc:
      permalink: true
      separator: "_"

plugins:
  - awesome-pages
  - glightbox
  - search:
      separator: '[\s\-\.]+'
      lang:
        - en

# Customization
extra_javascript:
  - "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js?config=TeX-MML-AM_CHTML"
extra_css:
  - "assets/css/custom.css"
extra:
  manifest: "manifest.json"
  generator: false
  social:
    - icon: "fontawesome/brands/github-alt"
      link: "https://github.com/sphere-drones"
    - icon: "fontawesome/brands/twitter"
      link: "https://x.com/spheredrones"
